spring.application.name=server
spring.datasource.url=jdbc:mysql://localhost:3306/petshop_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# API GHN
api.ghn.token=17a0a285-4b66-11f1-a973-aee5264794df
api.ghn.shop-id=200241
api.ghn.url.province=https://dev-online-gateway.ghn.vn/shiip/public-api/master-data/province
api.ghn.url.district=https://dev-online-gateway.ghn.vn/shiip/public-api/master-data/district
api.ghn.url.ward=https://dev-online-gateway.ghn.vn/shiip/public-api/master-data/ward
api.ghn.url.fee=https://dev-online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/fee